-- TalentSyncLinkSystem.lua
-- FR4b: clickable TalentInspect talent links for WoW 1.12.1.
--
-- Shift+LeftClick a TalentInspect talent while a chat edit box is open:
--   learned rank > 0 -> light-blue [Talent Name Rank X/Y]
--   unlearned rank 0 -> grey       [Talent Name Rank 1/Y]
--
-- Clicking the hyperlink shows that linked rank's talent information.
-- No network traffic is generated by links; they resolve from the same
-- Learned Data -> packaged TalentData authority stack already used by FR4a.

TalentSyncLinkSystem = TalentSyncLinkSystem or {}
local L = TalentSyncLinkSystem
L.VERSION = "1.0.3-GUARD2"
L.LINKTYPE = "vptalent"

local function normClass(c)
  if TalentInspectData_NormalizeClass then return TalentInspectData_NormalizeClass(c) end
  return c
end

local function esc(s)
  s=tostring(s or "")
  s=string.gsub(s,"%%","%%25")
  s=string.gsub(s,":","%%3A")
  s=string.gsub(s,"%|","%%7C")
  return s
end

local function unesc(s)
  s=string.gsub(s or "","%%7C","|")
  s=string.gsub(s,"%%3A",":")
  s=string.gsub(s,"%%25","%%")
  return s
end

local function activeEditBox()
  if ChatEdit_GetActiveWindow then
    local box=ChatEdit_GetActiveWindow()
    if box and box:IsVisible() then return box end
  end
  if ChatFrameEditBox and ChatFrameEditBox:IsVisible() then return ChatFrameEditBox end
  return nil
end

local function insertText(box,text)
  if not box or not text then return nil end
  if box.Insert then
    box:Insert(text)
  else
    box:SetText((box:GetText() or "")..text)
  end
  return 1
end

local function resolveTalent(classToken,tree,index,name,tier,col)
  classToken=normClass(classToken)
  local pos=nil
  if tier and col then pos="r"..tier.."c"..col end
  if TalentInspectData_FindTalent then
    local t=TalentInspectData_FindTalent(classToken,tree,name,pos,index)
    if t then return t end
  end
  local tr=TalentInspectData_GetTree and TalentInspectData_GetTree(classToken,tree)
  return tr and tr.talents and tr.talents[index] or nil
end

function L:BuildLink(button)
  if not button or not button.data then return nil end
  local t=button.data
  local classToken=normClass(button.classToken)
  local tree=tonumber(button.page) or 1
  local index=tonumber(t.index)
  local maxRank=tonumber(t.maxRank) or 1
  local actualRank=tonumber(t.rank) or 0
  if not classToken or not index then return nil end

  -- User-requested behavior: an unlearned talent links its first rank.
  local linkedRank=actualRank
  local color="|cff66ccff" -- light blue
  if linkedRank<=0 then
    linkedRank=1
    color="|cff808080" -- grey = not currently learned
  end
  if linkedRank>maxRank then linkedRank=maxRank end

  local name=t.name or t.sourceName or "Talent"
  local payload=table.concat({
    esc(classToken),tostring(tree),tostring(index),tostring(linkedRank),
    tostring(maxRank),esc(name),tostring(t.tier or 0),tostring(t.col or 0)
  },":")

  return color.."|H"..L.LINKTYPE..":"..payload.."|h["..
    name.." Rank "..linkedRank.."/"..maxRank.."]|h|r"
end

function TalentSyncLinkSystem_OnTalentClick(button,mouseButton)
  if mouseButton~="LeftButton" then return nil end
  if not IsShiftKeyDown or not IsShiftKeyDown() then return nil end
  local box=activeEditBox()
  if not box then return nil end
  local link=L:BuildLink(button)
  if not link then return nil end
  insertText(box,link)
  return 1
end

local function splitPayload(s)
  local out={}
  local start=1
  while 1 do
    local p=string.find(s or "",":",start,1)
    if not p then table.insert(out,string.sub(s or "",start)); break end
    table.insert(out,string.sub(s,start,p-1)); start=p+1
  end
  return out
end

local function linkedDescription(t,rank)
  if not t then return nil end
  if TalentInspectData_GetDescription then
    return TalentInspectData_GetDescription(t,rank)
  end
  return nil
end

function L:ShowLink(link)
  local prefix=L.LINKTYPE..":"
  if string.sub(link or "",1,string.len(prefix))~=prefix then return nil end

  local a=splitPayload(string.sub(link,string.len(prefix)+1))
  local classToken=unesc(a[1])
  local tree=tonumber(a[2]); local index=tonumber(a[3]); local rank=tonumber(a[4])
  local maxRank=tonumber(a[5]) or 1; local name=unesc(a[6])
  local tier=tonumber(a[7]); local col=tonumber(a[8])
  if not classToken or not tree or not index or not rank then return 1 end

  local t=resolveTalent(classToken,tree,index,name,tier,col)
  local shownName=(t and (t.name or t.sourceName)) or name or "Talent"
  local shownMax=(t and tonumber(t.maxRank)) or maxRank
  if rank<1 then rank=1 end
  if rank>shownMax then rank=shownMax end

  GameTooltip:SetOwner(UIParent,"ANCHOR_CURSOR")
  GameTooltip:ClearLines()
  GameTooltip:AddLine(shownName,1,0.82,0)
  GameTooltip:AddLine("Rank "..rank.." / "..shownMax,1,1,1)

  local desc=linkedDescription(t,rank)
  if desc and desc~="" then
    GameTooltip:AddLine(desc,1,0.82,0,1)
  else
    GameTooltip:AddLine("Talent description unavailable for this rank.",0.65,0.65,0.65,1)
  end

  local treeData=TalentInspectData_GetTree and TalentInspectData_GetTree(classToken,tree)
  if treeData and treeData.name then
    GameTooltip:AddLine(treeData.name.." Talent",0.55,0.75,1)
  end
  GameTooltip:Show()
  return 1
end

-- SetItemRef is the standard 1.12 hyperlink click path. Preserve every other
-- addon/game hyperlink by delegating unknown link types to the previous handler.
local oldSetItemRef=SetItemRef
function SetItemRef(link,text,button)
  if L:ShowLink(link) then return end
  if oldSetItemRef then return oldSetItemRef(link,text,button) end
end


-- FR4c: Native N TalentFrame linking -----------------------------------------
-- Hook Blizzard's local TalentFrame buttons only after Blizzard_TalentUI exists.
-- Existing click behavior is preserved; Shift+LeftClick is intercepted ONLY
-- when a chat edit box is active and a TalentInspect hyperlink can be inserted.

local function nativeSelectedTab()
  if TalentFrame and TalentFrame.selectedTab then
    return tonumber(TalentFrame.selectedTab) or 1
  end
  if TalentFrame and PanelTemplates_GetSelectedTab then
    local ok,id=pcall(PanelTemplates_GetSelectedTab,TalentFrame)
    if ok and id then return tonumber(id) or 1 end
  end
  return 1
end

function L:BuildNativeTalentLink(tab,index)
  tab=tonumber(tab) or 1
  index=tonumber(index)
  if not index or not GetTalentInfo then return nil end

  local name,icon,tier,col,rank,maxRank=GetTalentInfo(tab,index)
  if not name then return nil end

  local _,classToken=UnitClass("player")
  classToken=normClass(classToken)
  maxRank=tonumber(maxRank) or 1
  rank=tonumber(rank) or 0

  local linkedRank=rank
  local color="|cff66ccff"
  if linkedRank<=0 then
    linkedRank=1
    color="|cff808080"
  end
  if linkedRank>maxRank then linkedRank=maxRank end

  local payload=table.concat({
    esc(classToken),tostring(tab),tostring(index),tostring(linkedRank),
    tostring(maxRank),esc(name),tostring(tier or 0),tostring(col or 0)
  },":")

  return color.."|H"..L.LINKTYPE..":"..payload.."|h["..
    name.." Rank "..linkedRank.."/"..maxRank.."]|h|r"
end

function TalentSyncLinkSystem_OnNativeTalentClick(button,mouseButton)
  if mouseButton~="LeftButton" then return nil end
  if not IsShiftKeyDown or not IsShiftKeyDown() then return nil end
  local box=activeEditBox()
  if not box then return nil end

  local index=nil
  if button and button.GetID then index=button:GetID() end
  if not index or index<=0 then
    index=button and button.talentIndex
  end
  if not index then return nil end

  local link=L:BuildNativeTalentLink(nativeSelectedTab(),index)
  if not link then return nil end
  insertText(box,link)
  return 1
end

L.nativeHooks=L.nativeHooks or {}

local function hookNativeButton(button)
  if not button or L.nativeHooks[button] then return nil end
  if not button.GetScript or not button.SetScript then return nil end

  local oldClick=button:GetScript("OnClick")
  button:SetScript("OnClick",function()
    if TalentSyncLinkSystem_OnNativeTalentClick and
       TalentSyncLinkSystem_OnNativeTalentClick(this,arg1) then
      return
    end
    if oldClick then return oldClick() end
  end)

  L.nativeHooks[button]=1
  return 1
end

function L:InstallNativeTalentHooks()
  local installed=0

  -- Stock 1.12 Blizzard_TalentUI naming.
  for i=1,80 do
    local b=getglobal("TalentFrameTalent"..i)
    if b and hookNativeButton(b) then installed=installed+1 end
  end

  -- Some 1.12-derived/custom UIs use slightly different global prefixes.
  -- These probes are harmless when absent and make the hook tolerant of forks.
  for i=1,80 do
    local b=getglobal("PlayerTalentFrameTalent"..i)
    if b and hookNativeButton(b) then installed=installed+1 end
  end

  return installed
end

-- Blizzard_TalentUI is load-on-demand in stock 1.12, so install hooks both when
-- it appears and opportunistically if a custom client already created it.
local nativeHookEvents=CreateFrame("Frame")
nativeHookEvents:RegisterEvent("ADDON_LOADED")
nativeHookEvents:RegisterEvent("PLAYER_LOGIN")
nativeHookEvents:SetScript("OnEvent",function()
  if event=="ADDON_LOADED" then
    if arg1=="Blizzard_TalentUI" or TalentFrame then
      L:InstallNativeTalentHooks()
    end
  elseif event=="PLAYER_LOGIN" then
    if TalentFrame then L:InstallNativeTalentHooks() end
  end
end)

-- Immediate attempt for clients/UI packs that preload the talent frame.
if TalentFrame then
  L:InstallNativeTalentHooks()
end
